kind: Service
apiVersion: v1
metadata:
  name: appconfig-nodeport
  namespace: app-namespace
spec:
  type: NodePort
  selector:
    app: appconfig
  ports:
   - protocol: TCP
     port: 8888
     targetPort: 8888